{
 "title": "Mikrotik Monitoring",
 "description": "Mikrotik metrics (from mtik_exporter)",
 "tags": [
  "mikrotik",
  "mtik_exporter"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "ds", "query": "victoriametrics-datasource" },
   {
    "name": "node",
    "label": "Routerboard",
    "query": {
     "query": "label_values(mtik_exporter_system_identity_info,routerboard_name)"
    }
   },
   {
    "name": "netwatch_icmp_target",
    "query": {
     "query": "label_values(mtik_exporter_netwatch_icmp_rtt_avg{routerboard_name=\"$node\"},name)"
    }
   },
   {
    "name": "wg_if",
    "query": {
     "query": "label_values(mtik_exporter_wireguard_interfaces_info{routerboard_name=\"$node\"},name)"
    }
   },
   {
    "name": "interface",
    "query": {
     "query": "query_result(label_join(mtik_exporter_interface_rx_byte_total{routerboard_name = \"$node\", type != \"loopback\", type != \"wg\"}, \"desc\", \"  \", \"name\", \"comment\"))"
    }
   },
   {
    "name": "instance",
    "label": "Server",
    "query": {
     "query": "label_values(mtik_exporter_system_identity_info{routerboard_name=\"$node\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Identity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (name) (mtik_exporter_system_identity_info{routerboard_name=\"$node\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Routerboard HW",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (board_name) (mtik_exporter_system_uptime_total{routerboard_name=\"$node\"})",
     "legendFormat": "{{board_name}}"
    }
   ]
  },
  {
   "title": "Installed Packages",
   "type": "table",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "sum by (name, disabled) (mtik_exporter_installed_packages_info{routerboard_name=\"$node\"})"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "expr": "(1 - mtik_exporter_system_free_memory{routerboard_name=\"$node\"} / mtik_exporter_system_total_memory{routerboard_name=\"$node\"})*100",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "Used memory" },
     "legendFormat": "Used RAM Memory",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "expr": "mtik_exporter_system_cpu_load{routerboard_name=\"$node\"}",
     "legendFormat": "CPU Load"
    },
    {
     "expr": "(1 - mtik_exporter_system_free_hdd_space{routerboard_name=\"$node\"} / mtik_exporter_system_total_hdd_space{routerboard_name=\"$node\"})*100",
     "legendFormat": "HDD Utilization"
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "expr": "mtik_exporter_system_cpu_load{routerboard_name=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "CPU 1 load" },
     "legendFormat": "{{cpu}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "CPU Frequency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "expr": "mtik_exporter_system_cpu_frequency{routerboard_name=\"$node\"}*1000000",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "Used memory" },
     "legendFormat": "{{cpu}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtik_exporter_system_cpu_frequency{routerboard_name=\"$node\"}*1000000",
     "legendFormat": "{{cpu}} "
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mtik_exporter_system_routerboard_temperature{routerboard_name=\"$node\"}  ",
     "legendFormat": "__auto"
    },
    {
     "expr": "mtik_exporter_system_cpu_temperature{routerboard_name=\"$node\"}  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "General" },
     "expr": "sum by (current_version) (mtik_exporter_system_info{routerboard_name=\"$node\"})",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "System version and hw" },
     "legendFormat": "Current: {{current_version}}",
     "mode": 2,
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "expr": "sum by (latest_version) (mtik_exporter_system_info{routerboard_name=\"$node\"} * on(channel) group_left(latest_version) mtik_exporter_system_latest_version_info)",
     "legendFormat": "Latest: {{latest_version}}"
    },
    {
     "expr": "(mtik_exporter_system_info{routerboard_name=\"$node\"} * on(channel) group_left(latest_version) mtik_exporter_system_latest_version_built) - on(routerboard_name) mtik_exporter_installed_packages_build_time{routerboard_name=\"$node\", name=\"routeros\"}",
     "legendFormat": "Newest"
    }
   ]
  },
  {
   "title": "System uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "General" },
     "expr": "mtik_exporter_system_uptime_total{routerboard_name=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "System uptime" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (address, name, via) (mtik_exporter_active_users_last_login{routerboard_name=\"$node\"} * 1000)"
    }
   ]
  },
  {
   "title": "HDD Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "expr": "mtik_exporter_system_total_hdd_space{routerboard_name=\"$node\"} - mtik_exporter_system_free_hdd_space{routerboard_name=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "Used memory" },
     "legendFormat": "Used memory",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "Memory" },
     "expr": "mtik_exporter_system_total_hdd_space{routerboard_name=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "Total memory" },
     "legendFormat": "Total memory",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "expr": "mtik_exporter_system_hdd_bad_blocks_percent{routerboard_name=\"$node\"}",
     "legendFormat": "Bad Blocks"
    }
   ]
  },
  {
   "title": "HDD Wear Level",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "expr": "mtik_exporter_system_hdd_write_sector_count_total{routerboard_name=\"$node\"} * ((vector(2048) and on() (mtik_exporter_system_total_hdd_space{routerboard_name=\"$node\"} > 268435456)) or on() vector(512)) / mtik_exporter_system_total_hdd_space{routerboard_name=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "Used memory" },
     "legendFormat": "Wear Level",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "General" },
     "expr": "mtik_exporter_system_routerboard_voltage{routerboard_name=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "System version and hw" },
     "mode": 2,
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "IP Address",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (routerboard_address) (mtik_exporter_public_ip_address_info{routerboard_name=\"$node\"})",
     "legendFormat": "{{routerboard_address}}"
    }
   ]
  },
  {
   "title": "Public Address",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtik_exporter_public_ip_address_info{routerboard_name=\"$node\"}",
     "legendFormat": "{{public_address}}"
    },
    {
     "expr": "mtik_exporter_public_ip_address_info{routerboard_name=\"$node\", public_address_ipv6!=\"\"}",
     "legendFormat": "{{public_address_ipv6}}"
    },
    {
     "expr": "mtik_exporter_public_ip_address_info{routerboard_name=\"$node\"}",
     "legendFormat": "{{dns_name}}"
    }
   ]
  },
  {
   "title": "Active User Counts",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 5, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (address, name, via) (mtik_exporter_active_users_count{routerboard_name=\"$node\"})"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Routes",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(mtik_exporter_routes_info{routerboard_name=\"$node\", distance!=\"0\"}) + count((mtik_exporter_ipv6_routes_info{routerboard_name=\"$node\", distance!=\"0\"}) OR on() vector(0))",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Routes per protocol",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 2, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "count(mtik_exporter_routes_info{routerboard_name=\"$node\", distance!=\"0\", dynamic=\"true\"})",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "/errors on interface/" },
     "legendFormat": "ipv4 - dynamic",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "expr": "count(mtik_exporter_routes_info{routerboard_name=\"$node\", distance!=\"0\", dynamic=\"false\"})",
     "legendFormat": "ipv4 - static"
    },
    {
     "expr": "count(mtik_exporter_ipv6_routes_info{routerboard_name=\"$node\", distance!=\"0\", dynamic=\"true\"})",
     "legendFormat": "ipv6 - dynamic"
    },
    {
     "expr": "count(mtik_exporter_ipv6_routes_info{routerboard_name=\"$node\", distance!=\"0\", dynamic=\"false\"})",
     "legendFormat": "ipv6 - static"
    }
   ]
  },
  {
   "title": "Ethernet Ports: Full Duplex",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_by_label(mtik_exporter_interface_full_duplex{routerboard_name=\"$node\"}, \"name\")",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Interface Errors",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "rate(mtik_exporter_interface_rx_error_total{routerboard_name=\"$node\"}[$__rate_interval])",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "/errors on interface/" },
     "legendFormat": "In Errors | {{name}} {{comment}}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "expr": "rate(mtik_exporter_interface_tx_error_total{routerboard_name=\"$node\"}[$__rate_interval])",
     "legendFormat": "Out Errors | {{name}} {{comment}}"
    }
   ]
  },
  {
   "title": "Ethernet Ports: Status",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort_by_label_numeric(mtik_exporter_interface_status{routerboard_name=\"$node\"}, \"name\")",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Rates",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (comment, name) (mtik_exporter_interface_rate{routerboard_name=\"$node\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "POE",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "mtik_exporter_poe_info{routerboard_name=\"$node\"}"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(mtik_exporter_interface_rx_byte_total{routerboard_name=\"$node\", id=~\"$interface\"}[$__rate_interval])*8",
     "legendFormat": "In - {{name}} {{comment}}"
    },
    {
     "expr": "-rate(mtik_exporter_interface_tx_byte_total{routerboard_name=\"$node\", id=~\"$interface\"}[$__rate_interval])*8",
     "legendFormat": "Out - {{name}} {{comment}}"
    }
   ]
  },
  {
   "title": "IP Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(mtik_exporter_firewall_mangle_bytes_total{routerboard_name=\"$node\", action=\"passthrough\", comment=\"IPv4 In\"}[$__rate_interval])*8",
     "legendFormat": "{{comment}}"
    },
    {
     "expr": "rate(mtik_exporter_firewall_mangle_ipv6_bytes_total{routerboard_name=\"$node\", action=\"passthrough\", comment=\"IPv6 In\"}[$__rate_interval])*8",
     "legendFormat": "{{comment}}"
    },
    {
     "expr": "-rate(mtik_exporter_firewall_mangle_bytes_total{routerboard_name=\"$node\", action=\"passthrough\", comment=\"IPv4 Out\"}[$__rate_interval])*8",
     "legendFormat": "{{comment}}"
    },
    {
     "expr": "-rate(mtik_exporter_firewall_mangle_ipv6_bytes_total{routerboard_name=\"$node\", action=\"passthrough\", comment=\"IPv6 Out\"}[$__rate_interval])*8",
     "legendFormat": "{{comment}}"
    }
   ]
  },
  {
   "title": "Total In",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(mtik_exporter_firewall_mangle_bytes_total{\n    routerboard_name=\"$node\",\n    action=\"passthrough\",\n    comment=\"IPv4 In\"\n}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(mtik_exporter_firewall_mangle_ipv6_bytes_total{\n    routerboard_name=\"$node\",\n    action=\"passthrough\",\n    comment=\"IPv6 In\"\n}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Out",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(mtik_exporter_firewall_mangle_bytes_total{routerboard_name=\"$node\", action=\"passthrough\", comment=\"IPv4 Out\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(mtik_exporter_firewall_mangle_ipv6_bytes_total{routerboard_name=\"$node\", action=\"passthrough\", comment=\"IPv6 Out\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DHCP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {}
   ]
  },
  {
   "title": "DHCP Dynamic IPS",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "count by (host) (mtik_exporter_dhcp_lease_info{routerboard_name=\"$node\", dynamic=\"true\"})",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "__auto",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "DHCP Leases",
   "type": "table",
   "gridPos": { "h": 19, "w": 19, "x": 5, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "sum by (host_name, comment, mac_address, mac_vendor, active_address, address, address_lists, status) (sort_by_label_numeric(\r\nlabel_replace(label_replace(label_replace(label_replace(mtik_exporter_dhcp_lease_info{routerboard_name=\"$node\", active_address!=\"\"},\r\n\"ip-part1\", \"$1\", \"address\", \"([0-9]{1,3})\\\\.(.+)\"),\r\n\"ip-part2\", \"$2\", \"address\", \"([0-9]{1,3})\\\\.([0-9]{1,3})\\\\.(.+)\"),\r\n\"ip-part3\", \"$3\", \"address\", \"([0-9]{1,3})\\\\.([0-9]{1,3})\\\\.([0-9]{1,3})\\\\.(.+)\"),\r\n\"ip-part4\", \"$4\", \"address\", \"([0-9]{1,3})\\\\.([0-9]{1,3})\\\\.([0-9]{1,3})\\\\.([0-9]{1,3})\"),\r\n\"ip-part1\", \"ip-part2\", \"ip-part3\", \"ip-part4\"))"
    },
    {
     "expr": "sum by (mac_address) (mtik_exporter_dhcp_lease_expiry{routerboard_name=\"$node\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (mac_address) (mtik_exporter_dhcp_lease_last_seen{routerboard_name=\"$node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DHCP Leases by Server",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "count by(server) (mtik_exporter_dhcp_lease_info{routerboard_name=\"$node\", active_address!=\"\"})",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "{{ server }}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Total DHCP Leases",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "count(mtik_exporter_dhcp_lease_info{routerboard_name=\"$node\", active_address!=\"\"})",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "In - {{ server }}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Firewall",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Open Connections",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(mtik_exporter_connection_stats{routerboard_name=\"JP-RB5009\"}) * on (src_address) group_right(src_address, dst_addresses) (label_replace(mtik_exporter_dhcp_lease_info{routerboard_name=\"JP-RB5009\"}, \"src_address\", \"$1\", \"address\", \"(.*)\")) or on (src_address, dst_addresses) mtik_exporter_connection_stats{routerboard_name=\"JP-RB5009\"}"
      }
     ]
    },
    {
     "title": "Open Connections Stats",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sort_desc(mtik_exporter_connection_stats{routerboard_name=\"$node\"})",
       "legendFormat": "{{src_address}}"
      }
     ]
    },
    {
     "title": "Firewall Rules Traffic INPUT",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "application": { "filter": "Network" },
       "expr": "rate(mtik_exporter_firewall_filter_bytes_total{routerboard_name=\"$node\", chain=\"input\"}[$__rate_interval])*8",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "{{ comment }}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Firewall Rules Traffic FORWARD",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "application": { "filter": "Network" },
       "expr": "rate(mtik_exporter_firewall_filter_bytes_total{routerboard_name=\"$node\", chain=\"forward\"}[$__rate_interval])*8",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "{{ comment }}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    }
   ]
  },
  { "title": "ARP Entries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "Unknown Devices",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "sum by (interface, mac_address, address, dynamic, status) (sort_by_label(mtik_exporter_arp_entry_info{routerboard_name=\"$node\", dhcp_lease_type!=\"static\"}, \"interface\"))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MAC Table",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 87 },
   "targets": [
    {
     "expr": "sort_by_label(mtik_exporter_bridge_host_info{routerboard_name=\"$node\", dhcp_lease_type!=\"static\"}, \"interface\")",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 } },
  {
   "title": "Containers",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 95 },
   "targets": [
    {
     "expr": "sum by (comment, os, arch, root_dir, status) (mtik_exporter_container_running{routerboard_name=\"$node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Netwatch",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Netwatch Info",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 102 },
   "targets": [
    {
     "expr": "sum by (name, host, type, status) (mtik_exporter_netwatch_status{routerboard_name=\"$node\"})"
    },
    {
     "expr": "sum by (name, host, type, status) (mtik_exporter_netwatch_since{routerboard_name=\"$node\"} * 1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Netwatch Targets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 },
   "collapsed": true,
   "panels": [
    {
     "title": "$netwatch_icmp_target Ping",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
     "repeat": "netwatch_icmp_target",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "mtik_exporter_netwatch_icmp_rtt_avg{routerboard_name=\"$node\", name=\"${netwatch_icmp_target:raw}\"}",
       "legendFormat": "avg"
      },
      {
       "expr": "mtik_exporter_netwatch_icmp_rtt_max{routerboard_name=\"$node\", name=\"$netwatch_icmp_target\"}",
       "legendFormat": "max"
      },
      {
       "expr": "mtik_exporter_netwatch_icmp_rtt_min{routerboard_name=\"$node\", name=\"$netwatch_icmp_target\"}",
       "legendFormat": "min"
      }
     ]
    },
    {
     "title": "Packet loss",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 155 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "application": { "filter": "Network" },
       "expr": "sum_over_time(mtik_exporter_netwatch_icmp_loss_count{routerboard_name=\"$node\"}[$__rate_interval]) / sum_over_time(mtik_exporter_netwatch_icmp_sent_count{routerboard_name=\"$node\"}[$__rate_interval])",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "{{ name }}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "HTTP & TCP Response time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 163 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "mtik_exporter_netwatch_http_response_time{routerboard_name=\"$node\"} * mtik_exporter_netwatch_status{routerboard_name=\"$node\"}",
       "legendFormat": "https - {{name}}"
      },
      {
       "expr": "mtik_exporter_tcp_connect_time{routerboard_name=\"$node\"} * mtik_exporter_netwatch_status{routerboard_name=\"$node\"}",
       "legendFormat": "tcp-{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Wifi",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 113 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Remote Caps",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (identity, base_mac, version) (mtik_exporter_capsman_remote_caps_info{routerboard_name=\"$node\"})",
     "legendFormat": "{{identity}}"
    }
   ]
  },
  {
   "title": "Wifi Interfaces",
   "type": "table",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (name, configuration_ssid, channel, mac_address, master, tx_power) (mtik_exporter_wifi_interfaces_info{routerboard_name=\"$node\"})",
     "legendFormat": "{{identity}}"
    }
   ]
  },
  {
   "title": "Wifi Registrations",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 120 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "mtik_exporter_wifi_interface_authorized_peers{routerboard_name=\"$node\"} > 0",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "{{name}}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "expr": "sum(mtik_exporter_wifi_interface_authorized_peers{routerboard_name=\"$node\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Wifi Clients",
   "type": "table",
   "gridPos": { "h": 11, "w": 18, "x": 6, "y": 120 },
   "targets": [
    {
     "expr": "sum by (mac_address, interface, ssid, dhcp_address, dhcp_comment) (mtik_exporter_wifi_clients_devices_info{routerboard_name=\"$node\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (mac_address) (mtik_exporter_wifi_clients_signal_strength{routerboard_name=\"$node\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (mac_address) (mtik_exporter_wifi_clients_rx_rate{routerboard_name=\"$node\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (mac_address) (mtik_exporter_wifi_clients_tx_rate{routerboard_name=\"$node\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (mac_address) (mtik_exporter_wifi_clients_uptime{routerboard_name=\"$node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wifi Connected Peer Count",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "mtik_exporter_wifi_interface_authorized_peers{routerboard_name=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "{{ name }}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Wifi Clients Signal Strength",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "mtik_exporter_wifi_clients_signal_strength{routerboard_name=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "{{mac_address}} | {{dhcp_comment}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Wifi Clients Traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "rate(mtik_exporter_wifi_clients_rx_bytes_total{routerboard_name=\"$node\"}[$__rate_interval])*8",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "In | {{ mac_address }} | {{ dhcp_comment }}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "Network" },
     "expr": "-rate(mtik_exporter_wifi_clients_tx_bytes_total{routerboard_name=\"$node\"}[$__rate_interval])*8",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Outgoing traffic on interface ether1-gateway"
     },
     "legendFormat": "Out | {{ mac_address }} | {{ dhcp_comment }}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Data rates by CAP",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (interface,ssid)(rate(mtik_exporter_wifi_clients_rx_bytes_total{routerboard_name=\"$node\"} * on (mac_address) group_left(interface, ssid) mtik_exporter_wifi_clients_devices_info{routerboard_name=\"$node\"}[$__rate_interval]))*8",
     "legendFormat": "In | {{interface}} {{ssid}}"
    },
    {
     "expr": "-sum by (interface,ssid)(rate(mtik_exporter_wifi_clients_tx_bytes_total{routerboard_name=\"$node\"} * on (mac_address) group_left(interface, ssid) mtik_exporter_wifi_clients_devices_info{routerboard_name=\"$node\"}[$__rate_interval]))*8",
     "legendFormat": "Out | {{interface}} {{ssid}}"
    }
   ]
  },
  { "title": "IPv6 Neighbors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 157 } },
  {
   "title": "IPv6 Neighbors",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 158 },
   "targets": [
    {
     "expr": "sum by (address, dhcp_lease_type, dhcp_comment, dhcp_address, interface, mac_address, router, status) (last_over_time(mtik_exporter_ipv6_neighbor_info{routerboard_name=\"$node\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Traffic Per Interface", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 166 } },
  {
   "title": "$interface",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 167 },
   "repeat": "interface",
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(mtik_exporter_interface_rx_byte_total{routerboard_name=\"$node\", id=~\"$interface\"}[$__rate_interval])*8",
     "legendFormat": "In"
    },
    {
     "expr": "-rate(mtik_exporter_interface_tx_byte_total{routerboard_name=\"$node\", id=~\"$interface\"}[$__rate_interval])*8",
     "legendFormat": "Out"
    }
   ]
  },
  { "title": "Wireguard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 216 } },
  {
   "title": "Wireguard total traffic",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 217 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(mtik_exporter_interface_rx_byte_total{routerboard_name=\"$node\", type=\"wg\"}[$__rate_interval])*8",
     "legendFormat": "In | {{name}}"
    },
    {
     "expr": "rate(mtik_exporter_interface_tx_byte_total{routerboard_name=\"$node\", type=\"wg\"}[$__rate_interval])*-8",
     "legendFormat": "Out | {{name}}"
    }
   ]
  },
  {
   "title": "$wg_if",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 228 },
   "repeat": "wg_if",
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(mtik_exporter_wireguard_peer_rx_bytes_total{routerboard_name=\"$node\", interface=\"$wg_if\"}[$__rate_interval])*8",
     "legendFormat": "In | {{name}}"
    },
    {
     "expr": "-rate(mtik_exporter_wireguard_peer_tx_bytes_total{routerboard_name=\"$node\", interface=\"$wg_if\"})*8",
     "legendFormat": "Out | {{name}}"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 248 },
   "targets": [
    {
     "expr": "sum by (interface, name) (mtik_exporter_wireguard_peer_last_handshake{routerboard_name=\"$node\", current_endpoint_address=''} or mtik_exporter_wireguard_peer_last_handshake{routerboard_name=\"$node\"} > 500)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (interface, allowed_address, current_endpoint_address, name) (mtik_exporter_wireguard_peer_info{routerboard_name=\"$node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Zerotier Peers",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 261 },
   "targets": [
    {
     "expr": "sum by (zt_address, preferred_endpoint) (mtik_exporter_zerotier_peer_latency{routerboard_name=\"$node\", role=\"LEAF\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (name, zt_address, inactive, ip_address) (mtik_exporter_zerotier_controller_member_last_seen)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Zerotier Members",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 274 },
   "targets": [
    {
     "expr": "sum by (name, authorized, ip_address, zt_address) (mtik_exporter_zerotier_controller_member_last_seen{routerboard_name=\"$node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Simple Queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 287 },
   "collapsed": true,
   "panels": [
    {
     "title": "Simple Queue Rates",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 252 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "application": { "filter": "Network" },
       "expr": "rate(mtik_exporter_queue_simple_bytes_download_total{routerboard_name=\"$node\"}[$__rate_interval])*8",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "{{ name }} Download",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "Network" },
       "expr": "rate(mtik_exporter_queue_simple_bytes_upload_total{routerboard_name=\"$node\"}[$__rate_interval])*8",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "{{ name }} Upload",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Simple Queue Processed Bytes",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 252 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "application": { "filter": "Network" },
       "expr": "mtik_exporter_queue_simple_bytes_download_total{routerboard_name=\"$node\"}",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "{{ name }} Download",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "Network" },
       "expr": "mtik_exporter_queue_simple_bytes_upload_total{routerboard_name=\"$node\"}",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "{{ name }} Upload",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Simple Queue Queued Bytes",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 263 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "application": { "filter": "Network" },
       "expr": "rate(mtik_exporter_queue_simple_queued_bytes_upload_total{routerboard_name=\"$node\"}[$__rate_interval])",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "{{ name }} Download",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "Network" },
       "expr": "rate(mtik_exporter_queue_simple_queued_bytes_upload_total{routerboard_name=\"$node\"}[$__rate_interval])",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "{{ name }} Upload",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Simple Queue Dropped Bytes",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 263 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "application": { "filter": "Network" },
       "expr": "rate(mtik_exporter_queue_simple_dropped_download_total{routerboard_name=\"$node\"}[$__rate_interval])",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "{{ name }} Download",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "Network" },
       "expr": "rate(mtik_exporter_queue_simple_dropped_upload_total{routerboard_name=\"$node\"}[$__rate_interval])",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "{{ name }} Upload",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    }
   ]
  },
  {
   "title": "mtik_exporter Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 288 },
   "targets": [
    {}
   ]
  },
  {
   "title": "mtik_exporter Load Times (1min)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 289 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "sort_desc(increase(mtik_exporter_data_load_time_total{routerboard_name=\"$node\"}[$__interval]))",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "{{ name }}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "mtik_exporter Last Load Time",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 289 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "sort_desc(time() - mtik_exporter_data_load_last_run{routerboard_name=\"$node\"})",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "{{ name }}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "mtik_exporter Data Load Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 297 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "sort_desc(increase(mtik_exporter_data_load_time_total{routerboard_name=\"$node\"}[$__interval]))",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "{{name}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "mtik_exporter Data Load Time Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 305 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "sum(increase(mtik_exporter_data_load_time_total{routerboard_name=\"$node\"}[$__interval]))",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "Total",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "mtik_exporter Instance Data Load Time Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 313 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "sum(increase(mtik_exporter_data_load_time_total{instance=\"$instance\"}[$__interval]))",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "__auto",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "mtik_exporter Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 321 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "min(time() - mtik_exporter_data_load_last_run{routerboard_name=\"$node\"})",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "Total",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 329 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "scrape_duration_seconds{instance=\"$instance\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "Duration",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Scrape Sample Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 336 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "scrape_samples_post_metric_relabeling{instance=\"$instance\"}",
     "legendFormat": "Samples"
    }
   ]
  },
  {
   "title": "Process CPU Time Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 343 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "rate(process_cpu_seconds_total{job=\"mikrotik_mktxp\", instance=\"$instance\"}[$__interval])",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "Total",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Queue Tree",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 351 },
   "collapsed": true,
   "panels": [
    {
     "title": "Queue Tree Rates",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 291 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "application": { "filter": "Network" },
       "expr": "mtik_exporter_queue_tree_rates_total{routerboard_name=\"$node\"}*8",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "{{ name }}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Queue Tree Processed Bytes",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 291 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "application": { "filter": "Network" },
       "expr": "mtik_exporter_queue_tree_bytes_total{routerboard_name=\"$node\"}",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "{{ name }}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Queue Tree Queued Bytes",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 302 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "application": { "filter": "Network" },
       "expr": "rate(mtik_exporter_queue_tree_queued_bytes_total{routerboard_name=\"$node\"}[4m])",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "{{ name }}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Queue Tree Dropped Bytes",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 302 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "application": { "filter": "Network" },
       "expr": "rate(mtik_exporter_queue_tree_dropped_total{routerboard_name=\"$node\"}[4m])",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "{{ name }}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    }
   ]
  }
 ]
}